### ISSUE TITLE
txt Error

### ISSUE THREAD

**Issue by jesnstevens** [slu-soc5050/Week-10#1]
Hi @chris-prener. I'm receiving an r(199) error when I run my master/analysis do-files. I was trying to include the txt command along with the local macro but it's saying that the txt command is unrecognized. I'm running the master do-file so it is in a markDoc session. Any thoughts on why this might be happening?

**Comment by chris-prener** [comment]
Hi @jesnstevens,
I suspect you are missing double quotes around the static narrative text:

```stata
summarize mpg

txt "The mean of the variable `mpg` is " %10.3f r(mean)"."
```

@chris-prener

**Comment by jesnstevens** [comment]
@chris-prener, I've checked the quotes this is what I have in my file. 

`txt "**1.** The independent t-test suggests the the average score on the " ///
  "social science portion of the standard test from this data is " ///
  "statistically significant because P is " %10.3f `r(p)' ". This is " ///
  "smaller than .05 suggesting a rejection of the null hypothesis."`

**Comment by chris-prener** [comment]
Try to remove the back-tick and apostrophe from `r(p) in line 3. See if that helps...
